Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04-arm64"

  config.vm.provider "parallels" do |prl|
    prl.linked_clone = false

    prl.name   = "boundary"
    prl.memory = 1024
    prl.cpus   = 1
  end

  config.vm.network "private_network", ip: "10.5.0.5"

  config.vm.provision "shell", path: "../_common/setup.sh"
  config.vm.provision "shell", path: "setup.sh"
end
